import type { Metadata } from "next";
import { boldtextFont, primaryFont } from './fonts';
import "./globals.css";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${boldtextFont.variable} ${primaryFont.variable}`}>
        <div className="layout_navbar_container">
          <Link href={"/"} className="layout_navbar_logo_container">
            <div className="layout_navbar_logo"></div>
            <div className="layout_navbar_logo_text"></div>
          </Link>
          <div>
            <Link href={"/"} className="layout_navbar_menu_item">Home</Link>
            <Link href={"/bookmarks"} className="layout_navbar_menu_item">Bookmarks</Link>
          </div>
        </div>
        {children}
        <div className="layout_footer_container">
          <Link href={"/"} className="layout_navbar_logo_container">
            <div className="layout_navbar_logo"></div>
            <div className="layout_navbar_logo_text"></div>
          </Link>
        </div>
      </body>
    </html>
  );
}
